DataBoard/urls.py
from django.conf.urls import url
from . import views

app_name = 'board'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^save_records$', views.post_records, name='postRecords'),
    url(r'^login$', views.do_login, name='do_login'),
    url(r'^logout$', views.do_logout, name='do_logout'),
    url(r'^config$', views.config, name='config'),
    url(r'^timestamp$', views.last_timestamp, name='last_timestamp'),
    url(r'^datafile/(?P<filename>[\w\d\.\ ]+)/$', views.get_datafile, name='datafile'),
    url(r'^log_line$', views.log_line_db, name='log_line'),
    url(r'^notification$', views.notification, name='notification'),
    url(r'^get_log_list$', views.get_log_list, name='get_log_list'),
    url(r'^load_ddd_file$', views.load_ddd_file, name='load_ddd_file')

]

TachoBoard/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^tacho/', include('DataBoard.urls')),
    url(r'^admin/', admin.site.urls),
]

DataBoard/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime


class Company(models.Model):
    companyName = models.CharField(max_length=100)
    dateCreated = models.DateTimeField(auto_now_add=True)
    dataFilePath = models.CharField(max_length=512, default="")

    def __unicode__(self):
        return self.companyName


class Log(models.Model):

    levels = ['All','Critical', 'Error', 'Warning', 'Information', 'Verbose']

    logTime = models.DateTimeField(null=False, default=datetime.now)
    company = models.CharField(max_length=50)
    logLevel = models.IntegerField(null=False)
    logText = models.CharField(max_length=1000)

    def __unicode__(self):
        return "{} {}:{}".format(str(self.logTime), self.levels[self.logLevel], self.logText)

DataBoard/views.py
from __future__ import print_function
import os
import json
import urllib
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from django.http import Http404
import mimetypes
from utils import tacho_config
from utils import tacho_db
from utils import tacho_logs
from models import Log
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile


def index(request):

    if not request.user.is_authenticated():
        return redirect('board:do_login')

    if request.session.get("context"):
        context = request.session["context"]
    else:
        context = {}

    if not context.get("log_levels"):
        context["log_levels"] = Log.levels

    if not context.get('selected_log_level'):
        context['selected_log_level'] = 'Information'
        context['selected_log_level_index'] = Log.levels.index('Information')

    if request.POST.get('selected_log_level'):
        context['selected_log_level'] = request.POST.get('selected_log_level')
        context['selected_log_level_index'] = Log.levels.index(request.POST.get('selected_log_level'))

    context['company_list'] = tacho_config.get_config()

    if not settings.__getattr__('ROOT_PATH'):
        raise Http404("ROOT_PATH configuration parameter does not exists.")

    root_path = settings.__getattr__('ROOT_PATH')

    if request.POST.get('display_mode'):
        context['display_mode'] = request.POST.get('display_mode')
    else:
        if not context.get('display_mode'):
            context['display_mode'] = "LOG"

    if not context.get('selected_company'):
        context['selected_company'] = 'service'
        context['selected_company_name'] = "Tacho service"

    if not context.get('user_company'):
        context['user_company'] = '*'

    if request.user.is_authenticated:

        groups = request.user.groups.all()

        if len(groups) > 0:
            context['user_company'] = request.user.groups.all()[0].name
        else:
            context['user_company'] = "*"

        for company in context['company_list']:
            if company['company_code'] == request.POST.get('selected_company') or \
                            company['company_code'] == context['user_company']:

                context['selected_company_name'] = company['CompanyName']
                context['selected_company'] = company['company_code']
                context['company_code'] = company['company_code']
                context['data_file_path'] = company['DataFilesLocation']
                break

        if context['user_company'] == "*":
            if request.POST.get('selected_company') == "service":
                context['company_code'] = 'service'
                context['selected_company'] = 'service'
                context['selected_company_name'] = 'Tacho service'
                context['data_file_path'] = ""

    context['logs'], context['log_file_name'], context['log_content'] \
        = tacho_logs.get_log(request=request, root_path=root_path, selected_company=context['selected_company'],
                             log_level=context['selected_log_level_index'])

    if context.get('vehicleData'):
        del context['vehicleData']

    if context['display_mode'] == 'DATA' and context['user_company'] == "*":
        if request.POST.get("search"):
            json_data = tacho_db.filter_records(request.POST.get("imei"), request.POST.get("ts_from"),
                                                request.POST.get("ts_to"), request.POST.get("tm_from"),
                                                request.POST.get("tm_to"), context.get('selected_company'))
        else:
            json_data = tacho_db.read_all_records(company_name=context['selected_company'])

        context['vehicleData'] = json_data

    request.session['context'] = context

    return render(request=request, template_name='DataBoard/index.html', context=request.session['context'])


def do_login(request):
    if request.POST.get('username'):
        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
        if user:
            if user.is_active:
                login(request, user)
                return redirect('board:index')

    return render(request, 'DataBoard/login.html')


def do_logout(request):
    logout(request)
    return redirect('board:index')


@csrf_exempt
def config(request):

    if request.POST.get('config'):
        config_data = request.POST.get('config')
        json_data = json.loads(config_data)
        settings.__setattr__("DB_NAME", "Tacho"+json_data["CompanyName"])

    return HttpResponse('exit')


@csrf_exempt
def last_timestamp(request):
    if request.POST.get('company'):
        return HttpResponse(tacho_db.get_last_timestamp(request.POST.get('company')))


@csrf_exempt
def post_records(request):

    if request.POST.get('record'):
        record = request.POST.get('record')
        json_data = json.loads(record)
        tacho_db.write_records(json_data, request.POST.get('company'))

    request.POST = None
    return HttpResponse('exit')


def get_datafile(request, filename):

    file_path = '{}\{}'.format(request.session['context']['data_file_path'], filename)

    original_filename = filename

    fp = open(file_path, 'rb')
    response = HttpResponse(fp.read())
    fp.close()

    m_type, encoding = mimetypes.guess_type(original_filename)

    if m_type is None:
        m_type = 'application/octet-stream'

    if encoding is not None:
        response['Content-Encoding'] = encoding

    response['Content-Type'] = m_type
    response['Content-Length'] = str(os.stat(file_path).st_size)

    if u'WebKit' in request.META['HTTP_USER_AGENT']:
        # Safari 3.0 and Chrome 2.0 accepts UTF-8 encoded string directly.
        filename_header = 'filename=%s' % original_filename.encode('utf-8')
    elif u'MSIE' in request.META['HTTP_USER_AGENT']:
        # IE does not support internationalized filename at all.
        # It can only recognize internationalized URL, so we do the trick via routing rules.
        filename_header = ''
    else:
        # For others like Firefox, we follow RFC2231 (encoding extension in HTTP headers).
        filename_header = 'filename*=UTF-8\'\'%s' % urllib.quote(original_filename.encode('utf-8'))
    response['Content-Disposition'] = 'attachment; ' + filename_header

    return response

@csrf_exempt
def notification(request):

    if request.POST.get('message_text'):

        company_code = request.POST.get('company_code')

        conn = tacho_db.get_conn(company_name="")
        command = 'INSERT INTO "DataBoard_log" ("logLevel", "logText", "logTime", "company")' \
                  ' VALUES ({0}, \'{1}\', NOW(), \'{2}\')'.format(9, request.POST.get('message_text'), company_code)
        cur = conn.cursor()

        cur.execute(command)

        cur.close()

        conn.commit()

    return HttpResponse('OK')


@csrf_exempt
def log_line_db(request):

    if request.POST.get('logLevel'):

        print(request.POST.get('logLevel'))

        company_code = request.POST.get('company_code')

        conn = tacho_db.get_conn(company_name="")

        command = 'INSERT INTO "DataBoard_log" ("logLevel", "logText",' \
                  ' "logTime", "company") ' \
                  'VALUES ({0}, \'{1}\', NOW(), \'{2}\')'.format(request.POST.get('logLevel'),
                                                                 request.POST.get('logText'), company_code)

        cur = conn.cursor()

        cur.execute(command)

        cur.close()

        conn.commit()

    return HttpResponse('OK')


def get_log_list(request):
    context = request.session["context"]
    data = Log.objects.filter(company=context['company_code'])
    return HttpResponse(request, data)


@csrf_exempt
def load_ddd_file(request):

    try:
        if request.FILES:
            ddd_file = request.FILES.get('file')
            file_dir = '{}{}'.format(settings.__getattr__('MEDIA_ROOT'), ddd_file.name[2:10])

            if not os.path.exists(file_dir):
                os.makedirs(file_dir)

            file_path = '{}/{}'.format(file_dir, ddd_file.name)

            default_storage.save(file_path, ContentFile(ddd_file.read()))
    except:
        return HttpResponse('NOK')

    return HttpResponse('OK')

DataBoard/templates/DataBoard/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>T-Matix tachograph dashboard</title>

    <script src="{% static 'jquery/jquery-1.12.2.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'datatables/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'moment/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'datatables/css/jquery.dataTables.min.css' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
    {% block data_block %}
    {% endblock %}
</body>
</html>

DataBoard/templates/DataBoard/datatable.html
<script type="text/javascript" language="javascript">

 $(document).ready(function() {

	$('#oTable').dataTable({
	 "paging":true,
	 "pageLength": 18,
	 "select":'single',
	 "searching": false,
	 "columns": [{ "title": "Id" },
                 { "title": "Timestamp" },
                 { "title": "Files" },
                 { "title": "IMEI" },
                 { "title": "Number" },
                 { "title": "Time from" },
                 { "title": "Time to" },
                 { "title": "Data blocks" }] });
	});

</script>

<div class="panel panel-primary" style="margin: .5em .5em 0 0;">

        <a href="#" class="list-group-item active">
            <strong>{% if selected_company_name %}{{selected_company_name}} {% endif %} downloads</strong>
        </a>

        <div style="margin:.5em .5em 0em .5em;">
            <table id="oTable" class="display table-striped table-bordered table-hover" cellspacing="0" width="100%">
                <tbody>
                {%for row in vehicleData %}
                <tr>
                    <td>{{row.Id}}</td>
                    <td>{{row.Timestamp}}</td>
                    <td><a href="{% url 'board:datafile' row.Files %}" download="{{row.Files}}">{{row.Files}}</a></td>
                    <td>{{row.IMEI}}</td>
                    <td>{{row.Number}}</td>
                    <td>{{row.TachoTimeFrom}}</td>
                    <td>{{row.TachoTimeTo}}</td>
                    <td>{{row.DataBlocks}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

DataBoard/templates/DataBoard/db_log_list.html
<script type="text/javascript" language="javascript">

 $(document).ready(function() {

	$('#oTable').dataTable({
	 "paging":true,
	 "pageLength": 18,
	 "select":'single',
	 "searching": false,
	 "sorting":false,
	 "columns": [{ "title": "Time", "width": '10%' },
                 { "title": "Level", "width": '10%' },
                 { "title": "Log", "width": '80%' } ] });
	});

</script>

<div class="panel panel-primary" style="margin: .5em .5em 0 0;">

        <a href="#" class="list-group-item active">
            <strong>{% if selected_company_name %}{{selected_company_name}} {% endif %} tachograph logs</strong>
        </a>

        <div style="margin:.5em .5em 0em .5em;">
            <table id="oTable" class="display table-striped table-bordered table-hover" cellspacing="0" width="100%">
                <tbody>
                {%for log in logs %}

                   {% if log.logLevel == "Error" %}
						<tr style="color:red;">
				  {% endif %}

                  {% if log.logLevel == "Critical" %}
						<tr style="color:blue;">
				  {% endif %}

                    <td>{{log.logTime}}</td>
                    <td>{{log.logLevel}}</td>
                    <td>{{log.logText}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

DataBoard/templates/DataBoard/download_search.html
<div id="searchForm" class="modal" role="dialog">

    <div class="modal-dialog modal-mm">

        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Search</h4>
            </div>

            <form action="/tacho/"  method="POST" role="form" class="form-horizontal" style="margin-top:1em;">{% csrf_token %}

                    <div class="form-group" style="margin-left:1em;">
                        <div class="form-inline">
                                <label class="control-label col-sm-2" for="imei">IMEI</label>
                                <input type="text" class="form-control" name="imei"  id="imei">
                         </div>
                     </div>

                <div class="form-group" style="margin-left:1em;">
                     <div class="form-inline">

                         <label class="control-label col-sm-2" for="ts_from">Timestamp</label>
                                <div class='input-group date col-sm-3' id='ts_from'>
                                <input type='text' name="ts_from" class="form-control"/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>

                        <label class="control-label" for="ts_to">to</label>
                            <div class='input-group date col-sm-3' id='ts_to'>
                                <input type='text' name="ts_to" class="form-control"/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>

                    </div>
                           </div>


                <div class="form-group"  style="margin-left:1em;">
                     <div class="form-inline">

                         <label class="control-label col-sm-2" for="tm_from">Time from</label>
                                <div class='input-group date col-sm-3' id='tm_from'>
                                <input type='text'  name="tm_from" class="form-control"/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>

                        <label class="control-label" for="tm_to">to</label>
                            <div class='input-group date col-sm-3' id='tm_to'>
                                <input type='text'  name="tm_to" class="form-control"/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>

                    </div>
                           </div>

                <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Search</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>

               <input type="hidden" name="search" value="search"/>

            </form>

            </div>
    </div>
</div>

<script type="text/javascript">

 $(document).ready(function() {

            $(function () {
                $('#ts_from').datetimepicker({
                locale:'en',
                format: 'DD.MM.YYYY'
                });

                $('#ts_to').datetimepicker({
                locale:'en',
                format: 'DD.MM.YYYY'
                });

                $('#tm_from').datetimepicker({
                locale:'en',
                format: 'DD.MM.YYYY'
                });

                 $('#tm_to').datetimepicker({
                locale:'en',
                format: 'DD.MM.YYYY'
                });

            });
          });

        </script>

DataBoard/templates/DataBoard/header.html
{% load staticfiles %}

<div style="float: left;margin:0 .5em 0 0;">
    <img src="{% static 'img/tmatix-logo-scaled.png' %}"><img>
</div>

<div style="float: left;margin:0 .5em 0 0;">

                <form action="/tacho/" method="post">{% csrf_token %}
                    {% if display_mode == 'LOG' %}
                               <a class="btn btn-primary" style="text-decoration: none;font-size:16px;"  href="javascript:;" onclick="parentNode.submit();">Logs</a>
                    {% else %}
                               <a class="btn btn-default" style="text-decoration: none;font-size:16px;"  href="javascript:;" onclick="parentNode.submit();">Logs</a>
                                <input type="hidden" name="display_mode" value='LOG'>
                    {% endif %}
                  </form>
</div>

                    {% if display_mode == 'LOG' %}
<div style="float: left;margin:0 .5em 0 0;">
                            <div class="btn-group">

                           <button id="b_select_log_level" type="button" class="btn btn-primary" style="font-size:16px;width:10em;text-align:left;">
                                {% if selected_log_level %}
                                    {{selected_log_level}}
                                        {% else %}
                                            Log level
                                        {% endif %}
                        </button>

                          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                                  aria-haspopup="true" aria-expanded="false" style="font-size:16px;">
                            <span class="caret"></span>
                            <span class="sr-only"></span>
                          </button>

                        <ul class="dropdown-menu">
                            {%for level in log_levels %}
                            <li>
                                <form action="/tacho/" method="post">{% csrf_token %}
                                    <a style="text-decoration: none;margin:.5em 0 0 .5em;" href="javascript:;" onclick="parentNode.submit();">{{level}}</a>
                                    <input type="hidden" name="selected_log_level" value={{level}}>
                                </form>
                            </li>
                            {% endfor %}
                        </ul>

                    </div>

    </div>
                    {% endif %}

<div style="float: left;margin:0 .5em 0 0;">
    <form action="/tacho/" method="post">{% csrf_token %}
             {% if display_mode == 'DATA' %}
                       <a class="btn btn-primary" style="text-decoration: none;font-size:16px;"  href="javascript:;" >Downloads</a>
             {% else %}
                       <a class="btn btn-default" style="text-decoration: none;font-size:16px;"  href="javascript:;" onclick="parentNode.submit();">Downloads</a>
             {% endif %}
                        <input type="hidden" name="display_mode" value='DATA'>
    </form>
</div>

<div class="btn-group">

    <button id="b_select_company" type="button" class="btn btn-primary" style="font-size:16px;width:10em;text-align:left;">
      {% if selected_company_name %}
          {{selected_company_name}}
         {% else %}
             Company
         {% endif %}
    </button>

  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false" style="font-size:16px;">
    <span class="caret"></span>
    <span class="sr-only"></span>
  </button>

{% if user_company == "*"%}
  <ul class="dropdown-menu">
        {%for c in company_list %}
                <li>
                  <form action="/tacho/" method="post">{% csrf_token %}
                       <a style="text-decoration: none;margin:.5em 0 0 .5em;" href="javascript:;" onclick="parentNode.submit();">{{c.CompanyName}}</a>
                        <input type="hidden" name="selected_company" value={{c.company_code}}>
                  </form>
                </li>
        {% endfor %}

    <li role="separator" class="divider"></li>
                <li>
                  <form action="/tacho/" method="post">{% csrf_token %}
                       <a style="text-decoration: none;margin-left:.5em;" href="javascript:;" onclick="parentNode.submit();">Tacho service</a>
                        <input type="hidden" name="selected_company" value='service'>
                  </form>
                </li>
  </ul>
{% endif %}

</div>
{% if display_mode == 'DATA'%}
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#searchForm">Search</button>
{% endif %}

    <form action="/tacho/logout" style="float: right;margin:0 .5em 0 0;">
        <div class="btn-group">
    <div class="btn btn-default">{{ user.first_name }}</div>
        <button type="submit" class="btn btn-primary" style="float: right;margin:0 .5em 0 0;">Logout</button>
        </div>
    </form>

{% include "download_search.html" %}

DataBoard/templates/DataBoard/imports.html
<script src="{% static 'jquery/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

DataBoard/templates/DataBoard/index.html
{% extends 'DataBoard/base.html' %}

{% block data_block %}

<script type="text/javascript" language="javascript">
     $(document).ready(function() {

     if ( typeof log_text != 'undefined') {
        $('#log_text').scrollTop($('#log_text')[0].scrollHeight);}
	});

</script>

<div style="margin:0.5em 0 0 .5em; with:100%" >

{% include "header.html" %}

 {% if display_mode == 'LOG' %}

    <!--<table width="100%" style="margin-top:.5em;">
        <tr>
            <td style="vertical-align:top;width:30%">
                 {% include "log_list.html" %}
            </td>
            <td style="vertical-align:top;padding-left:1em;padding-right:1em;">
                 {% include "log_content.html" %}
            </td>
        </tr>
    </table>-->

{% include "db_log_list.html" %}

{% else %}
        {% include "datatable.html" %}
{% endif %}

</div>

{% endblock %}

DataBoard/templates/DataBoard/log_content.html
<div class="panel panel-primary">
                <div class="panel-heading">{{ log_file_name }}</div>
                <div class="panel-body">
                    <textarea class="form-control" rows="40"  readonly="true" id="log_text" style="border:none;">
                    {{log_content}}
                    </textarea>
                    </div>
                </div>

DataBoard/templates/DataBoard/log_list.html
 <div class="list-group">
                  <a href="#" class="list-group-item active">
                    <strong>{% if selected_company %}{{selected_company}} {% endif %} Logs</strong>
                  </a>
                   {%for log in logs %}

                    <form action="/tacho/" method="post">{% csrf_token %}
                        {% if log == log_file_name %}
                        <a class="list-group-item" style="background:#eee;text-decoration: none;" href="javascript:;" onclick="parentNode.submit();">{{log}}</a>
                        {% else %}
                            <a class="list-group-item " style="text-decoration: none;" href="javascript:;" onclick="parentNode.submit();">{{log}}</a>
                        {% endif %}
                        <input type="hidden" name="log_file" value={{log}}>
                    </form>

                    {%endfor%}
                </div>

DataBoard/templates/DataBoard/login.html
<!DOCTYPE html>

{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>T-Matix tachograph dashboard</title>
    <script src="{% static 'jquery/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
     <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/signin.css' %}">
    <link rel="icon" href="../../favicon.ico">

    <title>Title</title>
</head>
<body>
 <div class="container" style="margin-top:12em;">

      <form class="form-signin" action="#" method="POST">{% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="username" class="sr-only">Username</label>
        <input type="text" name='username' id="username" class="form-control" placeholder="User name" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" name="password" id="password"  style="margin-top:1em;" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div>
</body>
</html>

DataBoard/templates/DataBoard/static_files.html
{% load staticfiles %}
    <script src="{% static 'jquery/jquery-1.12.2.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'datatables/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'moment/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'datatables/css/jquery.dataTables.min.css' %}">